#############################################################################
# Makefile for building: gpio
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  gpio.pro
# Template: app
# Command: /home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/usr/bin/qt5/qmake -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile gpio.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe $(OE_QMAKE_CFLAGS) -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe $(OE_QMAKE_CXXFLAGS) -g -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/c++/5 -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5 -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQuick -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtNetwork -I../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore -I. -I../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/linux-oe-g++
QMAKE         = /home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gpio1.0.0
DISTDIR = /home/int-alwi/Downloads/Platform/moje/GPIO/.tmp/gpio1.0.0
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS)
LIBS          = $(SUBLIBS) -lsystemd -L/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib -lQt5Quick -L/home/int_prka/GDP/genivi-dev-platform/gdp-src-build/tmp/work/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/qtbase/5.5.1+gitAUTOINC+5afc431323-r0/build/lib -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
SED           = sed
STRIP         = $(OE_QMAKE_STRIP)

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		gpioclass.cpp qrc_qml.cpp
OBJECTS       = main.o \
		gpioclass.o \
		qrc_qml.o
DIST          = ../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_pre.prf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/qconfig.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_functions.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_config.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/linux-oe-g++/qmake.conf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_post.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exclusive_builds.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resolve_config.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_post.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/c++11.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qml_debug.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/warn_on.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resources.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/moc.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/opengl.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/uic.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/thread.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/testcase_targets.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exceptions.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/yacc.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/lex.prf \
		gpio.pro gpioclass.h main.cpp \
		gpioclass.cpp
QMAKE_TARGET  = gpio
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = gpio


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gpio.pro ../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/linux-oe-g++/qmake.conf ../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_pre.prf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/qconfig.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_functions.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_config.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/linux-oe-g++/qmake.conf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_post.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exclusive_builds.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_pre.prf \
		deployment.pri \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resolve_config.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_post.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/c++11.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qml_debug.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/warn_on.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resources.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/moc.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/opengl.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/uic.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/thread.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/testcase_targets.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exceptions.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/yacc.prf \
		../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/lex.prf \
		gpio.pro \
		qml.qrc \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Quick.prl \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Widgets.prl \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Gui.prl \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Qml.prl \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Network.prl \
		/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Core.prl
	$(QMAKE) -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile gpio.pro
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_pre.prf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/qconfig.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_clucene_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_compositor_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_core_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_dbus_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_declarative_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designer_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_enginio_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_gui_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_help_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_location_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_network_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_nfc_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_opengl_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_positioning_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qml_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quick_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_script_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sensors_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serialport_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_serviceframework_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_sql_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_svg_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_systeminfo_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_testlib_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uiplugin.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_uitools_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkit_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_websockets_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_widgets_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xml_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_functions.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt_config.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/linux-oe-g++/qmake.conf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/spec_post.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exclusive_builds.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_pre.prf:
deployment.pri:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resolve_config.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/default_post.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/c++11.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qml_debug.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/warn_on.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/qt.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/resources.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/moc.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/opengl.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/uic.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/unix/thread.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/testcase_targets.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/exceptions.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/yacc.prf:
../../../gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/mkspecs/features/lex.prf:
gpio.pro:
qml.qrc:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Quick.prl:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Widgets.prl:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Gui.prl:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Qml.prl:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Network.prl:
/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-oe-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile gpio.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents gpioclass.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp gpioclass.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		main.qml
	/home/int-alwi/Downloads/gdp-sdk/qemux86-64/sysroots/x86_64-oesdk-linux/usr/bin/qt5/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

main.o: main.cpp ../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets/QApplication \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets/qapplication.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcoreapplication.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_mips.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qeventloop.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qwindowdefs_win.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsize.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qcursor.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets/qwidget.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmargins.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpaintdevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qrect.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpalette.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qcolor.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qrgb.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qbrush.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qmatrix.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpolygon.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qregion.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qdatastream.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qline.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qtransform.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpainterpath.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qimage.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpixelformat.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qpixmap.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qfont.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qfontmetrics.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qfontinfo.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtWidgets/qsizepolicy.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qkeysequence.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qevent.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qurl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qurlquery.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qvector2d.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qtouchdevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qguiapplication.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qinputmethod.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQuick/QQuickView \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQuick/qquickview.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQuick/qquickwindow.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQuick/qtquickglobal.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qopengl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qt_windows.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qopengles2ext.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qopenglext.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qwindow.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QObject \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QEvent \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QMargins \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QRect \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qsurface.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qsurfaceformat.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtGui/qicon.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqml.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlprivate.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qtqmlglobal.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlparserstatus.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmlpropertyvaluesource.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmllist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmetaobject.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtQml/qqmldebug.h \
		gpioclass.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

gpioclass.o: gpioclass.cpp ../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QFile \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfile.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfiledevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiodevice.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobal.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qconfig.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qfeatures.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsystemdetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qprocessordetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcompilerdetection.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypeinfo.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtypetraits.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qsysinfo.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlogging.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qflags.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbasicatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qgenericatomic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_cxx11.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_gcc.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_msvc.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv7.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv6.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_armv5.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_ia64.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_mips.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_x86.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qatomic_unix.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qglobalstatic.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmutex.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qnumeric.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qnamespace.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstring.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qchar.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbytearray.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qrefcount.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qarraydata.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringbuilder.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qalgorithms.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qiterator.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qbytearraylist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringlist.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qregexp.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qstringmatcher.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcoreevent.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qscopedpointer.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmetatype.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvarlengtharray.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontainerfwd.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qisenum.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qobject_impl.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QTextStream \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qtextstream.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qlocale.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvariant.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qmap.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpair.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qdebug.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qhash.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qvector.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qpoint.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qset.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qcontiguouscache.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/qshareddata.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QDebug \
		gpioclass.h \
		../../../gdp-sdk/qemux86-64/sysroots/cortexa7hf-vfp-vfpv4-neon-poky-linux-gnueabi/usr/include/qt5/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpioclass.o gpioclass.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

